# Import the numpy package under the name np 

In [1]:
import numpy as np

# Print the numpy version and the configuration

In [3]:
print(np.__version__)

1.15.4


# Create a zero vector of size 10

In [5]:
np.zeros(shape=[10])
#np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

# Create a zero matrix of dimension (2,3)

In [7]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

# How to find the memory size of any array

In [15]:
x = np.zeros((4,5))
# to print total number of elements in a matrix vector
print("size = ",x.size)
# to print dimension
print("shape = ",x.shape)
#to print memory size of each element
print(x.itemsize)

size =  20
shape =  (4, 5)
8


# Create a null vector of size 10 but the fifth value which is 1

In [17]:
x = np.zeros(10)
x[4] = 1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


# Create a vector with values ranging from 10 to 19

In [18]:
x = np.arange(start=10, stop=20, step=1)
# x = np.arange(10,20,1) is same as above
print(x)

[10 11 12 13 14 15 16 17 18 19]


# Reverse a vector (first element becomes last)

In [20]:
np.flip(x)
# x[::-1] (slicing can also be used to reverse a vector instead of flip)

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

# Create a 3x3 matrix with values ranging from 0 to 8

In [27]:
x = np.arange(0,9,1)
x.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# Find indices of non-zero elements from [1,2,0,0,4,0]

In [30]:
x = np.array([1,2,0,0,4,0])
np.where(x != 0)
#np.nonzero(x)

(array([0, 1, 4]),)

# Create a 3x3 identity matrix

In [31]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Create a 3x3 array with random values

In [38]:
np.random.random((3,3)) #it will create a 3x3 array with random value between 0 and 1

array([[0.88703431, 0.19172729, 0.0014562 ],
       [0.3816061 , 0.75464254, 0.87980728],
       [0.15743187, 0.02224591, 0.25488119]])

In [43]:
np.random.randint(20,size=(3,3)) #it will create a 3x3 array random integer value less than 20

array([[16,  5,  8],
       [14,  8,  3],
       [ 2,  7, 13]])

# Create a 10x10 array with random values and find the minimum and maximum values 

In [95]:
x = np.random.random((10,10))
x.max(),x.min()

(0.9973063254374802, 0.014711438580563563)

#  Create a random vector of size 10 and find the mean value 

In [92]:
x = np.random.random(10)
print(x)
print("mean =",x.mean())

[0.23198951 0.59131093 0.11003733 0.80747692 0.97454502 0.1265232
 0.14531708 0.59115531 0.52297397 0.65384349]
mean = 0.475517276182328


# Create a 2d array with 1 on the border and 0 inside

In [54]:
x = np.ones((5,5))
x[1:4,1:4]=0    #also x[1:-1, 1:-1] = 0
print(x)

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

# How to add a border (filled with 0's) around an existing array

In [62]:
x = np.ones((4,4))
print(x)
y=np.pad(array=x, pad_width=1, mode="constant")
print(y)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


# Create a 5x5 matrix with values 1,2,3,4 as diagonal

In [63]:
x = np.array((1,2,3,4))
np.diag(x)

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

# Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [71]:
x = np.arange(15).reshape(5,3) # x is 5x3 matrix
y = np.arange(6).reshape(3,2)  # y is 3x2 matrix
np.dot(x,y)

array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

# How to find common values between two arrays

In [82]:
x = np.arange(1,10)
y=np.arange(5,15)
np.intersect1d(x,y)

array([5, 6, 7, 8, 9])

# computation

In [87]:
a = np.ones(3)
b = np.ones(3)*2
# a,b are three arrays, find out ((a+b)*(-a/2) 

np.add(a,b, out=b)
np.divide(a,2, out=a)
np.negative(a, out=a)
np.multiply(b,a)

array([-1.5, -1.5, -1.5])

# sort an array

In [100]:
x = np.random.random(size=10)
np.sort(x)

array([0.00622505, 0.17526892, 0.34352283, 0.44125449, 0.50920381,
       0.6325998 , 0.73286364, 0.82205216, 0.85638971, 0.95963788])